### ISSUE TITLE
Messages in chat do not persist

### ISSUE THREAD

**Issue by ikizhvatov** [Ksinia/erudite-client#9]
To reproduce:
1. in an active game, post a message in the game's chat, the message appears in the chat;
2. either:
  - exit the game following the "List of games" link and enter the same game again
  - or refresh the page with the game
3. see that the message is not in the chat.

Observed in Safari 13.1.2 on macOS and in DuckDuckGo browser on Android.

**Comment by Ksinia** [comment]
Thanks for the report.
Resolved by https://github.com/Ksinia/erudite-server/commit/6cd605563fe4bd82042c91f6f9d66349115615be
